# Generated by Django 2.0.2 on 2018-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_person_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
