# Generated by Django 2.0.2 on 2018-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180221_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='team',
        ),
        migrations.AddField(
            model_name='person',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='articles.Team'),
        ),
    ]
