# Generated by Django 2.0.2 on 2018-02-28 11:49

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180228_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_id',
            field=models.PositiveIntegerField(blank=True, validators=[articles.models.validate_civil_id]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
