# Generated by Django 2.0.2 on 2018-02-28 11:55

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180228_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_id',
            field=models.PositiveIntegerField(validators=[articles.models.validate_civil_id]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
