# Generated by Django 2.0.2 on 2018-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180228_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='articles.Team'),
        ),
    ]
